In [2]:

# example of a ordinal encoding
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

data = asarray([['red'], ['green'], ['blue']])
result   = OrdinalEncoder().fit_transform(data)


In [3]:
result

array([[2.],
       [1.],
       [0.]])

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("Ecommerce Customers")

In [6]:
df

Email  \
0        mstephenson@fernandez.com   
1                hduke@hotmail.com   
2                 pallen@yahoo.com   
3          riverarebecca@gmail.com   
4    mstephens@davidson-herman.com   
..                             ...   
495   lewisjessica@craig-evans.com   
496            katrina56@gmail.com   
497             dale88@hotmail.com   
498            cwilson@hotmail.com   
499      hannahwilson@davidson.com   

                                               Address            Avatar  \
0         835 Frank Tunnel\nWrightmouth, MI 82180-9605            Violet   
1       4547 Archer Common\nDiazchester, CA 06566-8576         DarkGreen   
2    24645 Valerie Unions Suite 582\nCobbborough, D...            Bisque   
3     1414 David Throughway\nPort Jason, OH 22070-1220       SaddleBrown   
4    14023 Rodriguez Passage\nPort Jacobville, PR 3...  MediumAquaMarine   
..                                                 ...               ...   
495  4483 Jones Motorway Suite 872\nLake Jamiefurt,...               Tan   
496  172 Owen Divide Suite 497\nWest Richard, CA 19320     PaleVioletRed   
497  0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...          Cornsilk   
498  680 Jennifer Lodge Apt. 808\nBrendachester, TX...              Teal   
499  49791 Rachel Heights Apt. 898\nEast Drewboroug...       DarkMagenta   

     Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0              34.497268    12.655651        39.577668              4.082621   
1              31.926272    11.109461        37.268959              2.664034   
2              33.000915    11.330278        37.110597              4.104543   
3              34.305557    13.717514        36.721283              3.120179   
4              33.330673    12.795189        37.536653              4.446308   
..                   ...          ...              ...                   ...   
495            33.237660    13.566160        36.417985              3.746573   
496            34.702529    11.695736        37.190268              3.576526   
497            32.646777    11.499409        38.332576              4.958264   
498            33.322501    12.391423        36.840086              2.336485   
499            33.715981    12.418808        35.771016              2.735160   

     Yearly Amount Spent  
0             587.951054  
1             392.204933  
2             487.547505  
3             581.852344  
4             599.406092  
..                   ...  
495           573.847438  
496           529.049004  
497           551.620145  
498           456.469510  
499           497.778642  

[500 rows x 8 columns]

In [9]:
df['Avatar_encoding'] = OrdinalEncoder().fit_transform(df.Avatar.values.reshape(-1,1))

In [10]:
df

Email  \
0        mstephenson@fernandez.com   
1                hduke@hotmail.com   
2                 pallen@yahoo.com   
3          riverarebecca@gmail.com   
4    mstephens@davidson-herman.com   
..                             ...   
495   lewisjessica@craig-evans.com   
496            katrina56@gmail.com   
497             dale88@hotmail.com   
498            cwilson@hotmail.com   
499      hannahwilson@davidson.com   

                                               Address            Avatar  \
0         835 Frank Tunnel\nWrightmouth, MI 82180-9605            Violet   
1       4547 Archer Common\nDiazchester, CA 06566-8576         DarkGreen   
2    24645 Valerie Unions Suite 582\nCobbborough, D...            Bisque   
3     1414 David Throughway\nPort Jason, OH 22070-1220       SaddleBrown   
4    14023 Rodriguez Passage\nPort Jacobville, PR 3...  MediumAquaMarine   
..                                                 ...               ...   
495  4483 Jones Motorway Suite 872\nLake Jamiefurt,...               Tan   
496  172 Owen Divide Suite 497\nWest Richard, CA 19320     PaleVioletRed   
497  0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...          Cornsilk   
498  680 Jennifer Lodge Apt. 808\nBrendachester, TX...              Teal   
499  49791 Rachel Heights Apt. 898\nEast Drewboroug...       DarkMagenta   

     Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0              34.497268    12.655651        39.577668              4.082621   
1              31.926272    11.109461        37.268959              2.664034   
2              33.000915    11.330278        37.110597              4.104543   
3              34.305557    13.717514        36.721283              3.120179   
4              33.330673    12.795189        37.536653              4.446308   
..                   ...          ...              ...                   ...   
495            33.237660    13.566160        36.417985              3.746573   
496            34.702529    11.695736        37.190268              3.576526   
497            32.646777    11.499409        38.332576              4.958264   
498            33.322501    12.391423        36.840086              2.336485   
499            33.715981    12.418808        35.771016              2.735160   

     Yearly Amount Spent  Avatar_encoding  
0             587.951054            132.0  
1             392.204933             25.0  
2             487.547505              6.0  
3             581.852344            114.0  
4             599.406092             80.0  
..                   ...              ...  
495           573.847438            127.0  
496           529.049004            104.0  
497           551.620145             18.0  
498           456.469510            128.0  
499           497.778642             27.0  

[500 rows x 9 columns]

In [20]:
df.Avatar_encoding.max() #0 - 137

137.0

In [18]:
df['Avatar'].value_counts()

SlateBlue               7
Cyan                    7
CadetBlue               7
GreenYellow             7
Teal                    7
                       ..
MediumPurple            1
CornflowerBlue          1
LightGoldenRodYellow    1
PowderBlue              1
LawnGreen               1
Name: Avatar, Length: 138, dtype: int64

In [22]:
len(df['Avatar'].unique())

138

In [71]:
py_dict = {'name':['arun','akash','jon','justin'],
          'age':[24,45,66,34],
          'color':['low','high','high','meduim']}

In [72]:
df1 = pd.DataFrame(py_dict)

In [35]:
df1['color_encoding'] = OrdinalEncoder().fit_transform(df1.color.values.reshape(-1,1))

In [36]:
df1

name  age   color  color_encoding
0    arun   24     low             1.0
1   akash   45    high             0.0
2     jon   66    high             0.0
3  justin   34  meduim             2.0

In [37]:
df3 = pd.get_dummies(df1.color)

In [38]:
df3

high  low  meduim
0     0    1       0
1     1    0       0
2     1    0       0
3     0    0       1

In [41]:
from sklearn.preprocessing import OneHotEncoder


TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]

In [65]:
df1['color encode with one'] = OneHotEncoder(drop='first', sparse=False).fit_transform(df1['color'].values.reshape(-1,1))

ValueError: Wrong number of items passed 2, placement implies 1

In [54]:
df1

name  age   color  color_encoding
0    arun   24     low             1.0
1   akash   45    high             0.0
2     jon   66    high             0.0
3  justin   34  meduim             2.0

In [50]:

# example of a dummy variable encoding
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
# define data
data = asarray([['red'], ['green'], ['blue']])
print(data)
# define one hot encoding
encoder = OneHotEncoder(drop='first', sparse=False)
# transform data
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 1.]
 [1. 0.]
 [0. 0.]]


In [69]:
df1['color']=OneHotEncoder(drop='first', sparse=False).fit_transform(df1['color'].values.reshape(-1,1))

In [70]:
df1

name  age  color  color_encoding
0    arun   24    1.0             1.0
1   akash   45    0.0             0.0
2     jon   66    0.0             0.0
3  justin   34    0.0             2.0

In [74]:
df1

name  age   color
0    arun   24     low
1   akash   45    high
2     jon   66    high
3  justin   34  meduim

In [80]:
OneHotEncoder(drop='first',sparse=False).fit_transform(df1['color'].values.reshape(-1,1))

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.]])

In [81]:
df1

name  age   color
0    arun   24     low
1   akash   45    high
2     jon   66    high
3  justin   34  meduim

In [84]:
df2 = pd.get_dummies(df1.color)

In [87]:
df4 = pd.concat([df1,df2],axis=1)

In [88]:
df4

name  age   color  high  low  meduim
0    arun   24     low     0    1       0
1   akash   45    high     1    0       0
2     jon   66    high     1    0       0
3  justin   34  meduim     0    0       1